CC=gcc
HCML=-lhcml

default:
	$(CC) example1.c -o example1 $(HCML)
	$(CC) example2.c -o example2 $(HCML)
	$(CC) example3.c -o example3 $(HCML)
	$(CC) example4.c -o example4 $(HCML)
	$(CC) example5.c -o example5 $(HCML)
